### ISSUE TITLE
Crash report 1.0-beta-1: IllegalArgumentException in UpcomingWCFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordCamp-Android#1]
After tapping the bookmark button in the "My WordCamps" tab:

```
E/CrashReporting(28342): java.lang.IllegalArgumentException: Operation is invalid after previous operation.
E/CrashReporting(28342):    at com.parse.ParseRemoveOperation.mergeWithPrevious(ParseRemoveOperation.java:49)
E/CrashReporting(28342):    at com.parse.ParseObject.performOperation(ParseObject.java:2733)
E/CrashReporting(28342):    at com.parse.ParseObject.removeAll(ParseObject.java:2857)
E/CrashReporting(28342):    at com.parse.ParsePush.unsubscribeInBackground(ParsePush.java:117)
E/CrashReporting(28342):    at org.wordcamp.UpcomingWCFragment.removeMyWC(UpcomingWCFragment.java:156)
E/CrashReporting(28342):    at org.wordcamp.adapters.UpcomingWCListAdapter$1.onClick(UpcomingWCListAdapter.java:97)
E/CrashReporting(28342):    at android.view.View.performClick(View.java:4756)
E/CrashReporting(28342):    at android.view.View$PerformClick.run(View.java:19748)
E/CrashReporting(28342):    at android.os.Handler.handleCallback(Handler.java:739)
E/CrashReporting(28342):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/CrashReporting(28342):    at android.os.Looper.loop(Looper.java:135)
E/CrashReporting(28342):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/CrashReporting(28342):    at java.lang.reflect.Method.invoke(Native Method)
E/CrashReporting(28342):    at java.lang.reflect.Method.invoke(Method.java:372)
E/CrashReporting(28342):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/CrashReporting(28342):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by aagam-shah** [comment]
It happens when the auth token of Parse is incorrect.

**Comment by maxme** [comment]
Ok, if we re-introduce Parse again, we would have to make the app works even with an incorrect token.

**Comment by aagam-shah** [comment]
Yeah will look into it before we re-introduce
